Repository UNLV-CS472-672/2024-S-GROUP1-Roadwatch, pull requests merged in 2024-04, with the labels that each got.

#93 Add workflow for Jest and Vitest testing
  .github/workflows/testing.yml
Labels: ready for review

#104 Create Stepper component for Register Page
  client/src/components/CreateAccount/CreateAccount.tsx
  client/src/components/SignUp/GeneralInfo/GeneralInfo.tsx
  client/src/components/SignUp/SignUp.tsx
  client/src/main.tsx
  client/src/pages/Register/Register.tsx
Labels: ready for review

#105 Add Marker server endpoints
  server/src/controllers/MarkerController.ts
  server/src/index.ts
  server/src/routes/Marker.ts
Labels: enhancement, backend, ready for review

#109 Created Post Data Model
  server/src/models/Community.ts
  server/src/models/Post.ts
Labels: backend

#101 Fully Integrated Push Notification API
  README.md
  client/.env.example
  client/public/sw.js
  client/src/assets/icons/logo_512.png
  client/src/components/CustomButton/CustomButton.module.scss
  client/src/components/CustomButton/CustomButton.tsx
  client/src/components/EnableNotification/EnableNotification.module.scss
  client/src/components/EnableNotification/EnableNotification.tsx
  client/src/pages/Home/Home.tsx
  client/src/pages/Login/Login.tsx
  client/src/scripts/sw.ts
  client/src/store/index.ts
  client/src/store/notification/index.ts
  client/src/store/notification/notification.slice.ts
  client/src/types/types.ts
  client/vite.config.ts
  package-lock.json
  server/.env.example
  server/src/controllers/NotificationController.ts
  server/src/controllers/UserController.ts
  server/src/middlewares/auth.ts
  server/src/models/User.ts
  server/src/routes/PushNotification.ts
Labels: documentation, enhancement, backend, ready for review, frontend

#120 Created CreatePost component
  client/src/components/CreatePost/CreatePost.module.scss
  client/src/components/CreatePost/CreatePost.tsx
  client/src/components/index.ts
Labels: ready for review

#119 Created Community GET Endpoint
  client/src/store/community/community.slice.ts
  client/src/store/community/index.ts
  client/src/types/types.ts
  server/src/controllers/CommunityController.ts
  server/src/index.ts
  server/src/routes/Community.ts
Labels: backend, ready for review

#133 Created forgotPassword Component
  client/src/components/ForgotPassword/ForgotPassword.module.scss
  client/src/components/ForgotPassword/ForgotPassword.tsx
  client/src/components/index.ts
  client/src/main.tsx
  client/src/pages/Forgot/Forgot.module.scss
  client/src/pages/Forgot/Forgot.tsx
  client/src/pages/Login/Login.module.scss
  client/src/pages/Login/Login.tsx
  client/src/pages/index.ts
Labels: component, ready for review

#122 Create Backend for Register Page
  client/src/components/CreateAccount/CreateAccount.tsx
  client/src/components/SignUp/GeneralInfo/GeneralInfo.tsx
  client/src/pages/Register/Register.tsx
Labels: ready for review

#139 Added Settings Page with Scalability Features
  .gitignore
  client/src/components/Header/Header.module.scss
  client/src/components/Navbar/Navbar.tsx
  client/src/components/Security/UpdatePassword/UpdatePassword.module.scss
  client/src/components/Security/UpdatePassword/UpdatePassword.tsx
  client/src/components/UserProfileUpdate/UserProfileUpdate.module.scss
  client/src/components/UserProfileUpdate/UserProfileUpdate.tsx
  client/src/components/index.ts
  client/src/main.tsx
  client/src/pages/SettingsPage/SettingsPage.module.scss
  client/src/pages/SettingsPage/SettingsPage.tsx
  client/src/pages/index.ts
  package-lock.json
Labels: ready for review, MVP

#134 Post Specific Post
  client/.eslintrc.cjs
  client/src/components/CommunityPost/CommunityPost.tsx
  client/src/components/Map/Map.tsx
  client/src/components/PostDiscussion/PostDiscussion.module.scss
  client/src/components/PostDiscussion/PostDiscussion.tsx
  client/src/main.tsx
  client/src/pages/CommunityX/CommunityX.tsx
  client/src/pages/Home/Home.tsx
  client/src/types/types.ts
  package-lock.json
  package.json
  server/src/controllers/MarkerController.ts
  server/src/controllers/PostControllers.ts
  server/src/index.ts
  server/src/models/Post.ts
  server/src/routes/Marker.ts
  server/src/routes/Posts.ts
Labels: ready for review, MVP

#138 Ensure Stylelint Compliance
  client/.stylelintrc.json
  client/src/components/CommunityCard/CommunityCard.module.scss
  client/src/components/CommunityPost/CommunityPost.module.scss
  client/src/components/CreateAccount/CreateAccount.module.scss
  client/src/components/CreatePost/CreatePost.module.scss
  client/src/components/CustomButton/CustomButton.module.scss
  client/src/components/EnableNotification/EnableNotification.module.scss
  client/src/components/ForgotPassword/ForgotPassword.module.scss
  client/src/components/Header/Header.module.scss
  client/src/components/LocationNotification/LocationNotification.module.scss
  client/src/components/Navbar/Navbar.module.scss
  client/src/components/PasswordField/PasswordField.module.scss
  client/src/components/ResetPassword/ResetPassword.module.scss
  client/src/components/ResetPasswordVerify/ResetPasswordVerify.module.scss
  client/src/components/SignUp/GeneralInfo/GeneralInfo.module.scss
  client/src/components/SignUp/SignUp.module.scss
  client/src/components/TextField/TextField.module.scss
  client/src/pages/Chat/Chat.module.scss
  client/src/pages/Community/Community.module.scss
  client/src/pages/CommunityX/CommunityX.module.scss
  client/src/pages/Forgot/Forgot.module.scss
  client/src/pages/Home/Home.module.scss
  client/src/pages/Instructions/Instructions.module.scss
  client/src/pages/Login/Login.module.scss
  client/src/pages/Profile/Profile.module.scss
  client/src/pages/Register/Register.module.scss
Labels: ready for review

#147 Created `ProfileIcon` Component
  client/src/components/CommunityCard/CommunityCard.tsx
  client/src/components/Header/Header.tsx
  client/src/components/ProfileIcon/ProfileIcon.tsx
  client/src/components/index.ts
Labels: ready for review

#136 Style update: `Navbar` component
  client/src/components/Navbar/Navbar.module.scss
  client/src/components/Navbar/Navbar.tsx
Labels: ready for review

#140 Style Audit: Ensure Consistent Font Families
  client/src/components/SignUp/SignUp.module.scss
  client/src/index.css
  client/src/main.tsx
Labels: ready for review, frontend

#141 Update Password and Update Profile Components for Settings Page
  client/src/components/Security/UpdatePassword/UpdatePassword.module.scss
  client/src/components/Security/UpdatePassword/UpdatePassword.tsx
  client/src/components/UserProfileUpdate/UserProfileUpdate.module.scss
  client/src/components/UserProfileUpdate/UserProfileUpdate.tsx
  client/src/pages/SettingsPage/SettingsPage.tsx
  client/src/store/user/user.slice.ts
  server/src/controllers/UserController.ts
  server/src/routes/User.ts
Labels: ready for review, MVP

#165 Final Fixes (Style + Functionality)
  client/src/components/Header/Header.module.scss
  client/src/components/Header/Header.tsx
  client/src/pages/Home/Home.tsx
  client/src/store/marker/marker.slice.ts
  server/src/controllers/MarkerController.ts
  server/test/routes/marker.test.ts
Labels: ready for review
